#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KEYS_DIR="$ROOT_DIR/keys/android"
ANDROID_DIR="$ROOT_DIR/android"

mkdir -p "$KEYS_DIR"

KEYSTORE_PATH="$KEYS_DIR/release.keystore"
PROPS_PATH="$ANDROID_DIR/keystore.properties"

if [[ -f "$KEYSTORE_PATH" ]]; then
  echo "Keystore already exists: $KEYSTORE_PATH"
  echo "Abort to avoid overwriting. If you really want to regenerate, delete it first."
  exit 1
fi

if ! command -v keytool >/dev/null 2>&1; then
  echo "keytool not found. Install a JDK (e.g. via Android Studio) and try again."
  exit 1
fi

KEY_ALIAS="${ANDROID_KEY_ALIAS:-toyutoyu}"

DNAME="${ANDROID_DNAME:-CN=toyutoyu, OU=app, O=toyutoyu, L=Tokyo, S=Tokyo, C=JP}"

# For non-interactive mode, passwords can be set via env vars or file
if [[ -n "${ANDROID_KEYSTORE_PASSWORD:-}" ]]; then
  STORE_PASSWORD="$ANDROID_KEYSTORE_PASSWORD"
else
  read -r -s -p "Keystore password (will be saved to android/keystore.properties): " STORE_PASSWORD
  echo
fi

if [[ -z "$STORE_PASSWORD" ]]; then
  echo "Error: Password cannot be empty."
  exit 1
fi

if [[ -n "${ANDROID_KEY_PASSWORD:-}" ]]; then
  KEY_PASSWORD="$ANDROID_KEY_PASSWORD"
else
  KEY_PASSWORD="${STORE_PASSWORD}"
fi

# Generate keystore
keytool -genkeypair -v \
  -keystore "$KEYSTORE_PATH" \
  -alias "$KEY_ALIAS" \
  -keyalg RSA \
  -keysize 2048 \
  -validity 10000 \
  -storepass "$STORE_PASSWORD" \
  -keypass "$KEY_PASSWORD" \
  -dname "$DNAME" \
  >/dev/null

# Write Gradle properties (ignored by git)
cat > "$PROPS_PATH" <<EOF
# Auto-generated by scripts/android-generate-keystore.sh
# This file is ignored by git.

storeFile=../keys/android/release.keystore
storePassword=$STORE_PASSWORD
keyAlias=$KEY_ALIAS
keyPassword=$KEY_PASSWORD
EOF

chmod 600 "$PROPS_PATH" || true

echo "Done."
echo "- Keystore: $KEYSTORE_PATH"
echo "- Gradle props: $PROPS_PATH"
echo
echo "Next: cd mobile/android && ./gradlew bundleRelease"
